import { Provider } from "@/layout/provider";
import { Navbar } from "@/layout";
import "@/public/globals.css";
import "@/public/fontAwasome.css";

export const metadata = {
	title: "Conf Plus",
	description: "Generated by Conf Plus",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Provider>
					<Navbar />
					{children}
				</Provider>
			</body>
		</html>
	);
}
